#[derive(Copy)]
pub enum ID {
    C,
    Fast,
    Cold,
    GHC,
    HiPE,
    WebKitJS,
    AnyReg,
    PreserveMost,
    PreserveAll,
    FirstTargetCC,
    X86StdCall,
    X86FastCall,
    ARMAPCS,
    ARMAAPCS,
    ARMAAPCSVFP,
    MSP430INTR,
    X86ThisCall,
    PTXKernel,
    PTXDevice,
    SPIRFUNC,
    SPIRKERNEL,
    IntelOCLBI,
    X8664SysV,
    X8664Win64,
}
impl ID {
    pub fn from_ffi(value: ::ffi::llvm_CallingConv_ID) -> ID {
        match value {
            ::ffi::llvm_CallingConv_ID::C => ID::C,
            ::ffi::llvm_CallingConv_ID::Fast => ID::Fast,
            ::ffi::llvm_CallingConv_ID::Cold => ID::Cold,
            ::ffi::llvm_CallingConv_ID::GHC => ID::GHC,
            ::ffi::llvm_CallingConv_ID::HiPE => ID::HiPE,
            ::ffi::llvm_CallingConv_ID::WebKit_JS => ID::WebKitJS,
            ::ffi::llvm_CallingConv_ID::AnyReg => ID::AnyReg,
            ::ffi::llvm_CallingConv_ID::PreserveMost => ID::PreserveMost,
            ::ffi::llvm_CallingConv_ID::PreserveAll => ID::PreserveAll,
            ::ffi::llvm_CallingConv_ID::X86_StdCall => ID::X86StdCall,
            ::ffi::llvm_CallingConv_ID::X86_FastCall => ID::X86FastCall,
            ::ffi::llvm_CallingConv_ID::ARM_APCS => ID::ARMAPCS,
            ::ffi::llvm_CallingConv_ID::ARM_AAPCS => ID::ARMAAPCS,
            ::ffi::llvm_CallingConv_ID::ARM_AAPCS_VFP => ID::ARMAAPCSVFP,
            ::ffi::llvm_CallingConv_ID::MSP430_INTR => ID::MSP430INTR,
            ::ffi::llvm_CallingConv_ID::X86_ThisCall => ID::X86ThisCall,
            ::ffi::llvm_CallingConv_ID::PTX_Kernel => ID::PTXKernel,
            ::ffi::llvm_CallingConv_ID::PTX_Device => ID::PTXDevice,
            ::ffi::llvm_CallingConv_ID::SPIR_FUNC => ID::SPIRFUNC,
            ::ffi::llvm_CallingConv_ID::SPIR_KERNEL => ID::SPIRKERNEL,
            ::ffi::llvm_CallingConv_ID::Intel_OCL_BI => ID::IntelOCLBI,
            ::ffi::llvm_CallingConv_ID::X86_64_SysV => ID::X8664SysV,
            ::ffi::llvm_CallingConv_ID::X86_64_Win64 => ID::X8664Win64,
        }
    }
    pub fn to_ffi(self) -> ::ffi::llvm_CallingConv_ID {
        match self {
            ID::C => ::ffi::llvm_CallingConv_ID::C,
            ID::Fast => ::ffi::llvm_CallingConv_ID::Fast,
            ID::Cold => ::ffi::llvm_CallingConv_ID::Cold,
            ID::GHC => ::ffi::llvm_CallingConv_ID::GHC,
            ID::HiPE => ::ffi::llvm_CallingConv_ID::HiPE,
            ID::WebKitJS => ::ffi::llvm_CallingConv_ID::WebKit_JS,
            ID::AnyReg => ::ffi::llvm_CallingConv_ID::AnyReg,
            ID::PreserveMost => ::ffi::llvm_CallingConv_ID::PreserveMost,
            ID::PreserveAll => ::ffi::llvm_CallingConv_ID::PreserveAll,
            ID::FirstTargetCC => ::ffi::llvm_CallingConv_ID::X86_StdCall,
            ID::X86StdCall => ::ffi::llvm_CallingConv_ID::X86_StdCall,
            ID::X86FastCall => ::ffi::llvm_CallingConv_ID::X86_FastCall,
            ID::ARMAPCS => ::ffi::llvm_CallingConv_ID::ARM_APCS,
            ID::ARMAAPCS => ::ffi::llvm_CallingConv_ID::ARM_AAPCS,
            ID::ARMAAPCSVFP => ::ffi::llvm_CallingConv_ID::ARM_AAPCS_VFP,
            ID::MSP430INTR => ::ffi::llvm_CallingConv_ID::MSP430_INTR,
            ID::X86ThisCall => ::ffi::llvm_CallingConv_ID::X86_ThisCall,
            ID::PTXKernel => ::ffi::llvm_CallingConv_ID::PTX_Kernel,
            ID::PTXDevice => ::ffi::llvm_CallingConv_ID::PTX_Device,
            ID::SPIRFUNC => ::ffi::llvm_CallingConv_ID::SPIR_FUNC,
            ID::SPIRKERNEL => ::ffi::llvm_CallingConv_ID::SPIR_KERNEL,
            ID::IntelOCLBI => ::ffi::llvm_CallingConv_ID::Intel_OCL_BI,
            ID::X8664SysV => ::ffi::llvm_CallingConv_ID::X86_64_SysV,
            ID::X8664Win64 => ::ffi::llvm_CallingConv_ID::X86_64_Win64,
        }
    }
}
